### ISSUE TITLE
データベース設計をする

### ISSUE THREAD

**Issue by hikarook94** [hikarook94/setlist-helper#13]
- [ ] 保存先ストレージの種類を決める
- [ ] ER図を作成する

**Comment by hikarook94** [comment]
モデルがどの程度の規模になるか、DB設計まわり、マイグレーションファイル・テストデータまで用意する

**Comment by hikarook94** [comment]
#76 で追加したコントローラーやその他のファイルを削除する

**Comment by hikarook94** [comment]
ER図を作成しました。
ジャケット画像はCarrierWaveでSongのcover_imageにファイル名の文字列で保存される想定をしています。
参考にした記事：https://pikawaka.com/rails/carrierwave

```mermaid
erDiagram
    SONG ||--o{ SONG_SETLIST : ""
    SETLIST ||--o{ SONG_SETLIST : ""
    SONG {
        int id
        string name
        string artist
        int duration_ms
        text memo
        string key
        string cover_image
    }
    SETLIST {
        int id
        string title
        int total_time
        int set_time
    }
    SONG_SETLIST {
        int id
        int song_id
        int setlist_id
    }
```

**Comment by satou54** [comment]
## songsテーブル

- keyは幅が決まっているのであればinteger型にしてenumで定義するのも良さそうです。（stringでも良いと思うのでお任せします）

## song_setlistテーブル

- 確か並び順をユーザーが決められる仕様だった気がするので並び順を制御するカラムが必要そうです。

## その他

- 細かいですが、railsだと作成日時と更新日時はcreated_atとupdated_atですね
- これも細かいですが、setlistsテーブルにもcreated_atとupdated_atを追加した方が良さそうです

**Comment by hikarook94** [comment]
```mermaid
erDiagram
    SONG ||--o{ SONG_SETLIST : ""
    SONG ||--o{ SCORE : ""
    SETLIST ||--o{ SONG_SETLIST : ""
    SONG {
        int id
        string name
        string artist
        int duration_ms
        text memo
        string key
        string cover_image
        date created_at
        date updated_at
    }
    SETLIST {
        int id
        string title
        int total_time
        int set_time
        date created_at
        date updated_at
    }
    SONG_SETLIST {
        int id
        int song_id
        int setlist_id
        int position
        date created_at
        date updated_at
    }
    SCORE {
        int id
        int song_id
        float score
        date created_at
        date updated_at
    }
```

**Comment by hikarook94** [comment]
レビューを元にアップデートしました。

- Scoreテーブル
  - scoreをratingに変更
  - keyをtranspositionに変更
  - transpositionが取る範囲を-7~+7に変更
  - transpositionの型をTINYINTに変更（RailsでTINYINT(4)に指定可能）
  - duration_msをduration_timeに変更
- Setlistテーブル
  - total_timeをduration_timeに変更
  - set_timeをtarget_duration_timeに変更（ユーザーが設定する。ランダムに選ぶ際の目標値）
- Scoreテーブル
  - scoreカラムをratingに変更



|Song|レパートリー曲|
|---|---|
|name|曲名|
|artist|アーティスト名|
|duration_time|曲の長さ（ミリ秒）|
|memo|メモ書き|
|transposition|曲を歌うときのキー（-7〜+7）|
|cover_image|ジャケット写真のファイル名|


|Score|曲の得点|
|---|---|
|rating|得点|

|Setlist|セットリスト|
|---|---|
|title|セットリストのタイトル|
|duration_time|含まれている曲の合計時間（ミリ秒）|
|target_duration_time|ユーザーが設定した目標合計時間（ミリ秒）|

```mermaid
erDiagram
    SONG ||--o{ SONG_SETLIST : ""
    SONG ||--o{ SCORE : ""
    SETLIST ||--o{ SONG_SETLIST : ""
    SONG {
        int id
        string name
        string artist
        int duration_time
        text memo
        tinyint transposition
        string cover_image
        date created_at
        date updated_at
    }
    SETLIST {
        int id
        string title
        int duration_time
        int target_duration_time
        date created_at
        date updated_at
    }
    SONG_SETLIST {
        int id
        int song_id
        int setlist_id
        int position
        date created_at
        date updated_at
    }
    SCORE {
        int id
        int song_id
        float rating
        date created_at
        date updated_at
    }
```

**Comment by shoynoi** [comment]
`SetList` テーブルで  `duration_time` を保持するのはどのような意図があるでしょうか？

紐づいている `Song` から算出できる値なので保持しなくても良いのかなーと思いました。
セットリストの曲を変えるたびに `duration_time` の値を変える必要があったり、（あまりないかもですが）Songの `duration_time` が変わった時もセットリスト側も併せて変更する必要があったりで整合性を保つのが面倒そうな気がしています

**Comment by hikarook94** [comment]
@shoynoi 
コメントありがとうございます。
Setlistのduration_timeは確かに持っておく必要はないですね。Songから算出するようにします。

|Song|レパートリー曲|
|---|---|
|name|曲名|
|artist|アーティスト名|
|duration_time|曲の長さ（ミリ秒）|
|memo|メモ書き|
|transposition|曲を歌うときのキー（-7〜+7）|
|cover_image|ジャケット写真のファイル名|


|Score|曲の得点|
|---|---|
|rating|得点|

|Setlist|セットリスト|
|---|---|
|title|セットリストのタイトル|
|target_duration_time|ユーザーが設定した目標合計時間（ミリ秒）|

```mermaid
erDiagram
    SONG ||--o{ SONG_SETLIST : ""
    SONG ||--o{ SCORE : ""
    SETLIST ||--o{ SONG_SETLIST : ""
    SONG {
        int id
        string name
        string artist
        int duration_time
        text memo
        tinyint transposition
        string cover_image
        date created_at
        date updated_at
    }
    SETLIST {
        int id
        string title
        int target_duration_time
        date created_at
        date updated_at
    }
    SONG_SETLIST {
        int id
        int song_id
        int setlist_id
        int position
        date created_at
        date updated_at
    }
    SCORE {
        int id
        int song_id
        float rating
        date created_at
        date updated_at
    }
```

**Comment by hikarook94** [comment]
Seedデータ作成は #91 でやることにします。
